### ISSUE TITLE
Segfault when using Lux.Conv with CUDA

### ISSUE THREAD

**Issue by srikumarks** [LuxDL/Lux.jl#386] opened 2023-08-22 11:58 UTC
The following program segfaults on my Ubuntu 20 x86_64bit machine with one Tesla T4.

```julia
using Lux, LuxCUDA, Random
function segfaulter()
    rng = MersenneTwister(1234)
    gdev = Lux.gpu_device() # Changing to cpu_device() works fine
    x = rand(rng,Float32,(16,32,1)) |> gdev;
    m = Lux.Conv((5,), 32=>32, tanh, groups=32) # Tried variants too. Seems like a problem with Lux.Conv
    ps, st = Lux.setup(rng, m) .|> gdev
    r = Lux.apply(m,x,ps,st)
end
segfaulter()
```

Changing the model to a `Lux.Dense` works fine though.

```julia
using Lux, LuxCUDA, Random
function worksfine()
    rng = MersenneTwister(1234)
    gdev = Lux.gpu_device()
    x = rand(rng,Float32,(32,10)) |> gdev;
    m = Lux.Dense(32=>32,tanh)
    ps, st = Lux.setup(rng, m) .|> gdev
    r = Lux.apply(m,x,ps,st)
end
worksfine()
```

Using Lux v0.5.2 on Julia v1.9.2 and my CUDA.versioninfo() is as below -
```
CUDA runtime 12.1, artifact installation
CUDA driver 12.1
NVIDIA driver 525.85.12, originally for CUDA 12.0

CUDA libraries: 
- CUBLAS: 12.1.3
- CURAND: 10.3.2
- CUFFT: 11.0.2
- CUSOLVER: 11.4.5
- CUSPARSE: 12.1.0
- CUPTI: 18.0.0
- NVML: 12.0.0+525.85.12

Julia packages: 
- CUDA: 4.4.0
- CUDA_Driver_jll: 0.5.0+1
- CUDA_Runtime_jll: 0.6.0+0

Toolchain:
- Julia: 1.9.2
- LLVM: 14.0.6
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: Tesla T4 (sm_75, 14.745 GiB / 15.000 GiB available)
```

**Comment by srikumarks** [comment] 2023-08-23 03:37
Pasting the core dump here for reference. The reference to line 10 in seg2.jl is the `Lux.apply` line in the function.

```
[41564] signal (11.1): Segmentation fault
in expression starting at /home/ubuntu/cleo/seg2.jl:10
unknown function (ip: 0x7f1686c436ff)
unknown function (ip: 0x7f1686d612c5)
unknown function (ip: 0x7f1686d61b86)
cublasLtMatmul at /usr/local/cuda/lib64/libcublasLt.so.11 (unknown line)
unknown function (ip: 0x7f16535795b5)
_Z22fft1_convolution_tiledIff6float2fE13cudnnStatus_tP12cudnnContextPKT_S6_PT2_P17cudnnTensorStructP17cudnnFilterStructiiP22cudnnConvolutionStructSA_PvT0_SG_bbS8_S8_ at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn3cnn12Fft_1d_TiledIff6float2fE21execute_internal_implERKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn3cnn15EngineInterface7executeERKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn3cnn15EngineContainerIL24cudnnBackendEngineName_t4EE21execute_internal_implERKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn3cnn15EngineInterface7executeERKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZNK5cudnn3cnn26AutoTransformationExecutor16execute_pipelineERNS0_15EngineInterfaceERKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZNK5cudnn3cnn22BatchPartitionExecutorclERNS0_15EngineInterfaceEPS2_RKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn3cnn28GeneralizedConvolutionEngineINS0_15EngineContainerIL24cudnnBackendEngineName_t4EEEE21execute_internal_implERKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn3cnn15EngineInterface7executeERKNS_7backend11VariantPackEP11CUstream_st at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn7backend7executeEP12cudnnContextRNS0_13ExecutionPlanERNS0_11VariantPackE at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn7backend14EnginesAlgoMapI25cudnnConvolutionFwdAlgo_tLi8EE15execute_wrapperEP12cudnnContextS2_RNS0_13ExecutionPlanERNS0_11VariantPackE at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn7backend18convolutionForwardEP12cudnnContextPKvPK17cudnnTensorStructS4_PK17cudnnFilterStructS4_PK22cudnnConvolutionStruct25cudnnConvolutionFwdAlgo_tPvmbS4_S4_S4_PK21cudnnActivationStructS7_SF_ at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
_ZN5cudnn3cnn18convolutionForwardEP12cudnnContextPKvPK17cudnnTensorStructS4_PK17cudnnFilterStructS4_PK22cudnnConvolutionStruct25cudnnConvolutionFwdAlgo_tPvmS4_S7_SF_ at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
unknown function (ip: 0x7f16530049bc)
_Z13findAlgorithmI20find_get_conv_params22cudnnConvolutionStruct25cudnnConvolutionFwdAlgo_t33cudnnConvolutionFwdAlgoPerfStructLi8ELb0EE13cudnnStatus_tT_iPiPT2_ at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
cudnnFindConvolutionForwardAlgorithmEx at /home/ubuntu/.julia/artifacts/46618accf53d4306ae450d749de3cb080111ac3b/lib/libcudnn_cnn_infer.so (unknown line)
macro expansion at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/libcudnn.jl:3039 [inlined]
#441 at /home/ubuntu/.julia/packages/CUDA/tVtYo/lib/utils/call.jl:27
#1 at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/libcudnn.jl:17 [inlined]
retry_reclaim at /home/ubuntu/.julia/packages/CUDA/tVtYo/src/pool.jl:348
check at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/libcudnn.jl:16 [inlined]
cudnnFindConvolutionForwardAlgorithmEx at /home/ubuntu/.julia/packages/CUDA/tVtYo/lib/utils/call.jl:26 [inlined]
#652 at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:193 [inlined]
#with_workspace#4 at /home/ubuntu/.julia/packages/CUDA/tVtYo/lib/utils/call.jl:79
with_workspace at /home/ubuntu/.julia/packages/CUDA/tVtYo/lib/utils/call.jl:58 [inlined]
#with_workspace#1 at /home/ubuntu/.julia/packages/CUDA/tVtYo/lib/utils/call.jl:55 [inlined]
with_workspace at /home/ubuntu/.julia/packages/CUDA/tVtYo/lib/utils/call.jl:55 [inlined]
with_workspace at /home/ubuntu/.julia/packages/CUDA/tVtYo/lib/utils/call.jl:55 [inlined]
cudnnConvolutionFwdAlgoPerf at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:192
unknown function (ip: 0x7f17581a3327)
_jl_invoke at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2940
#cudnnConvolutionForwardAD#646 at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:102
cudnnConvolutionForwardAD at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:101 [inlined]
#cudnnConvolutionForwardWithDefaults#645 at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:96
unknown function (ip: 0x7f175819bb3d)
_jl_invoke at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2940
cudnnConvolutionForwardWithDefaults at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:57
#cudnnConvolutionForward!#644 at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:53 [inlined]
cudnnConvolutionForward! at /home/ubuntu/.julia/packages/cuDNN/YkZhm/src/convolution.jl:53 [inlined]
#conv!#12 at /home/ubuntu/.julia/packages/NNlib/aaK3U/ext/NNlibCUDACUDNNExt/conv.jl:78
conv! at /home/ubuntu/.julia/packages/NNlib/aaK3U/ext/NNlibCUDACUDNNExt/conv.jl:69 [inlined]
#conv#239 at /home/ubuntu/.julia/packages/NNlib/aaK3U/src/conv.jl:88 [inlined]
conv at /home/ubuntu/.julia/packages/NNlib/aaK3U/src/conv.jl:83 [inlined]
_conv at /home/ubuntu/.julia/packages/Lux/3rwok/src/utils.jl:125 [inlined]
Conv at /home/ubuntu/.julia/packages/Lux/3rwok/src/layers/conv.jl:126 [inlined]
apply at /home/ubuntu/.julia/packages/LuxCore/2w7nj/src/LuxCore.jl:103
unknown function (ip: 0x7f1758193168)
_jl_invoke at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2940
segfaulter at /home/ubuntu/cleo/seg2.jl:8
unknown function (ip: 0x7f1758172e9f)
_jl_invoke at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
do_call at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/interpreter.c:126
eval_value at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/interpreter.c:226
eval_stmt_value at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/interpreter.c:177 [inlined]
eval_body at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/interpreter.c:624
jl_interpret_toplevel_thunk at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/interpreter.c:762
jl_toplevel_eval_flex at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/toplevel.c:912
jl_toplevel_eval_flex at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/toplevel.c:856
ijl_toplevel_eval_in at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/toplevel.c:971
eval at ./boot.jl:370 [inlined]
include_string at ./loading.jl:1903
_jl_invoke at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2940
_include at ./loading.jl:1963
include at ./Base.jl:457
jfptr_include_32440.clone_1 at /home/ubuntu/.julia/juliaup/julia-1.9.2+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2940
exec_options at ./client.jl:307
_start at ./client.jl:522
jfptr__start_43375.clone_1 at /home/ubuntu/.julia/juliaup/julia-1.9.2+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
true_main at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/jlapi.c:573
jl_repl_entrypoint at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/jlapi.c:717
main at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/cli/loader_exe.c:59
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
Allocations: 12952551 (Pool: 12944541; Big: 8010); GC: 20
Segmentation fault (core dumped)
```

**Comment by avik-pal** [comment] 2023-08-23 17:56
Added this test to CI, and it seem to pass even on CI.

Try running the CUDA.jl tests on your machine. From the error it seems the origin is cuBLAS.

**Comment by avik-pal** [comment] 2023-09-24 01:22
Closing this since it can't be reproduced!

**Closed by avik-pal** 2023-09-24 01:22 UTC
Labels: can't reproduce
